### ISSUE TITLE
jetty-maven-plugin: 8.0.0.M2    "java.lang.ClassNotFoundException: org.eclipse.jetty.server.session.AbstractSession"

### ISSUE THREAD

**Issue by jacarrichan** [ovea-deprecated/jetty-session-redis#8]
wiki show"JEDIS website (tested on version 1.5.2),Jetty website (tested on version 8.0.0.M2)"
But  an exception occur   on my computer , the exception  stack context:
## please  create a  demo  project for  user;  I think  it is very good.

[WARNING] FAILED ContextHandlerCollection@5f4d9eed: java.lang.NoClassDefFoundError: org/eclipse/jetty/server/session/AbstractSession
[WARNING] FAILED HandlerCollection@60fd0a7c: java.lang.NoClassDefFoundError: org/eclipse/jetty/server/session/AbstractSession
[WARNING] Error starting handlers
java.lang.NoClassDefFoundError: org/eclipse/jetty/server/session/AbstractSession
        at java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2493)
        at java.lang.Class.getConstructors(Class.java:1517)
        at org.eclipse.jetty.xml.XmlConfiguration.newObj(XmlConfiguration.java:639)
        at org.eclipse.jetty.xml.XmlConfiguration.itemValue(XmlConfiguration.java:949)
        at org.eclipse.jetty.xml.XmlConfiguration.value(XmlConfiguration.java:874)
        at org.eclipse.jetty.xml.XmlConfiguration.newObj(XmlConfiguration.java:633)
        at org.eclipse.jetty.xml.XmlConfiguration.itemValue(XmlConfiguration.java:949)
        at org.eclipse.jetty.xml.XmlConfiguration.value(XmlConfiguration.java:874)
        at org.eclipse.jetty.xml.XmlConfiguration.set(XmlConfiguration.java:301)
        at org.eclipse.jetty.xml.XmlConfiguration.configure(XmlConfiguration.java:263)
        at org.eclipse.jetty.xml.XmlConfiguration.configure(XmlConfiguration.java:205)
        at org.eclipse.jetty.plus.webapp.EnvConfiguration.configure(EnvConfiguration.java:98)
        at org.eclipse.jetty.webapp.WebAppContext.configure(WebAppContext.java:473)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1174)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:598)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:496)
        at org.mortbay.jetty.plugin.JettyWebAppContext.doStart(JettyWebAppContext.java:175)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:55)
        at org.eclipse.jetty.server.handler.HandlerCollection.doStart(HandlerCollection.java:226)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:164)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:55)
        at org.eclipse.jetty.server.handler.HandlerCollection.doStart(HandlerCollection.java:226)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:55)
        at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:93)
        at org.eclipse.jetty.server.Server.doStart(Server.java:244)
        at org.mortbay.jetty.plugin.JettyServer.doStart(JettyServer.java:67)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:55)
        at org.mortbay.jetty.plugin.AbstractJettyMojo.startJetty(AbstractJettyMojo.java:447)
        at org.mortbay.jetty.plugin.AbstractJettyMojo.execute(AbstractJettyMojo.java:387)
        at org.mortbay.jetty.plugin.JettyRunMojo.execute(JettyRunMojo.java:555)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:106)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:317)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:152)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:555)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.server.session.AbstractSession
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:259)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:235)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:227)
        ... 52 more
[INFO] Started SelectChannelConnector@0.0.0.0:8080
[INFO] Started Jetty Server

**Comment by jacarrichan** [comment]
I  found a Demo  at  https://github.com/Ovea/jetty-session-redis/blob/jetty-session-redis-2.3.ga/src/test/java/StartServers.java

**Comment by jacarrichan** [comment]
java.lang.NoClassDefFoundError: org/eclipse/jetty/server/session/AbstractSession

The  classpath  has two servlet-api ,one is  2.5 and  the other one  is 3.0 ,remove 2.5 from classpath, The exception  disappear.
